name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: "40 5 * * *" # every day at 5:40

jobs:
  check:
    name: Check

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3
      - run: cargo --version --verbose
      - uses: Swatinem/rust-cache@v2
      - uses: r7kamura/rust-problem-matchers@v1.1.0
      - name: "Run `cargo check`"
        run: cargo check --all-targets --all

  test:
    name: Test

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v3
      - run: cargo --version --verbose
      - uses: Swatinem/rust-cache@v2

      # install QEMU
      - name: Install QEMU (Linux)
        run: sudo apt update && sudo apt install qemu-system-x86
        if: runner.os == 'Linux'
      - name: Install QEMU (macOS)
        run: brew install qemu
        if: runner.os == 'macOS'
        env:
          HOMEBREW_NO_AUTO_UPDATE: 1
          HOMEBREW_NO_BOTTLE_SOURCE_FALLBACK: 1
          HOMEBREW_NO_INSTALL_CLEANUP: 1
      - name: Install QEMU (Windows)
        run: |
          choco install qemu --version 2021.5.5
          echo "$Env:Programfiles\qemu" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        if: runner.os == 'Windows'
        shell: pwsh
      - name: "Print QEMU Version"
        run: qemu-system-x86_64 --version

      - uses: r7kamura/rust-problem-matchers@v1.1.0
      - name: Run api tests
        run: cargo test -p bootloader_api
      - name: Run integration tests
        run: cargo test

  fmt:
    name: Check Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: r7kamura/rust-problem-matchers@v1.1.0
      - run: cargo fmt --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cargo --version --verbose
      - uses: Swatinem/rust-cache@v2
      - uses: r7kamura/rust-problem-matchers@v1.1.0
      - run: cargo clippy --all --all-targets
