name: Trigger Release

on:
  push:
    branches:
      - "main"

jobs:
  check:
    name: Trigger Release
    runs-on: ubuntu-latest
    timeout-minutes: 10
    environment: trigger_release

    steps:
      - uses: actions/checkout@v3

      - name: "Install Python Libraries"
        run: python -m pip install --user -r .github/workflows/trigger-release/requirements.txt

      - name: "Run release script"
        run: "python3 .github/workflows/trigger-release/trigger-release.py"
        env:
          GITHUB_TOKEN: ${{ secrets.RUST_OSDEV_AUTORELEASE_TOKEN }}
